### ISSUE TITLE
Only one GraphQLQueryProvider is used for Schema validation

### ISSUE THREAD

**Issue by juergen-albert** [geckoprojects-org/org.gecko.graphql#9]
It appears, that when multiple `GraphQLQueryProvider` are registered, only the first one seems to be recognized. In the MDO project we register multiple and only the first one is recognized: https://github.com/de-jena/MDO/blob/main/de.jena.mdo.graphql/src/de/jena/mdo/graphql/query/MDOGraphQLQueryProvider.java

Please note that MDO uses a Version that predates the update to the newer GraphQL Version. Thus this may already be fixed.

**Comment by ideas-into-software** [comment]
@juergen-albert

`org.gecko.whiteboard.graphql.schema.GeckoGraphQLSchemaBuilder` uses list to store instances of `graphql.kickstart.servlet.osgi.GraphQLQueryProvider`, and iterates over that list, i.e.:

 - `private final List<GraphQLQueryProvider> queryProviders = new ArrayList<>()`
 
 - `org.gecko.whiteboard.graphql.schema.GeckoGraphQLSchemaBuilder.add(GraphQLQueryProvider)`
 
 - `org.gecko.whiteboard.graphql.schema.GeckoGraphQLSchemaBuilder.getQueryTypeBuilder()`
 

`org.gecko.whiteboard.graphql.servlet.OsgiGraphQLWhiteboard` only delegates to instance of `org.gecko.whiteboard.graphql.schema.GeckoGraphQLSchemaBuilder` and calls its methods (e.g. `org.gecko.whiteboard.graphql.schema.GeckoGraphQLSchemaBuilder.add(GraphQLQueryProvider)`, etc.)

Therefore, it should not be a problem to use multiple instances of `graphql.kickstart.servlet.osgi.GraphQLQueryProvider`.

MDO project (https://github.com/de-jena/MDO) would need to be upgraded to latest Jakarta Servlet API 6.x compatible Apache Felix (https://github.com/apache/felix-dev/tree/jakarta-servlet-6) and Gecko GraphQL (https://github.com/geckoprojects-org/org.gecko.graphql/pull/8) as a prerequisite to verify this. Do you want me to take care of this ?

**Comment by juergen-albert** [comment]
We can't update the MDO Project yet, as there e.g. the OpenApi stuff, which does not work with the jakarta servlet yet due to some OSGi metadata that is wrong. 

Regarding the issue at hand: The old Code was quite similar and I would have expected it to work as well. Could you please create an integration test to verify that it does?

Please capture the following 2 scenarios:

1. Register 2 Seperate implementations of a Query and type provider.
2. Register 2 Instances of the same implementieren of a query and type provider (similar to what happens in MDO. 
3.

**Comment by ideas-into-software** [comment]
@juergen-albert 

I updated existing PR (https://github.com/geckoprojects-org/org.gecko.graphql/pull/8) and there you will find additional integration test you asked for (i.e. https://github.com/ideas-into-software/org.gecko.graphql/blob/jakarta-servlet-6-x/org.gecko.whiteboard.graphql.emf.example.test/src/org/gecko/whiteboard/graphql/emf/example/test/MultiProviderTest.java), which covers both use cases you mentioned (two instances of same, etc.); see commit: https://github.com/geckoprojects-org/org.gecko.graphql/pull/8/commits/3ed128d948f04717f12b52aa36a1a64b0bf941fc

The issue you were referring to appears to be brought over from previous version of Gecko GraphQL, i.e. before my commits (see e.g. https://github.com/geckoprojects-org/org.gecko.graphql/commit/779c4f5091da9aa3ccc847d66c14d6d2373d36f0#diff-1a766e7f6eec453f8f3e9b601d8674000334c4e8bc38e4ead8bdf63518101d4c); exception was thrown at `graphql.schema.impl.GraphQLTypeCollectingVisitor.assertUniqueTypeObjects(GraphQLNamedType, GraphQLType)`  – there, you’ll see GraphQL Java requires all types to have unique names.

As a follow up to my earlier question regarding upgrade of MDO project, if you are referring to this issue https://github.com/swagger-api/swagger-core/issues/4354 as a blocker, you filed this 7 months ago and nothing was done about this so far. Do you want to wait more or should we take care of this so MDO upgrade can proceed ? Especially now, that Gecko GraphQL issue you reported is fixed, and it’s upgraded to Jakarta. 

One thing to keep in mind is that even latest version (as of 2023/08/20) of Swagger Jakarta (2.2.15) supports only Jakarta Servlet API 5.x, while latest Gecko GraphQL uses Jakarta Servlet 6.x..

**Comment by ideas-into-software** [comment]
@juergen-albert As agreed, here is PR https://github.com/geckoprojects-org/org.gecko.graphql/pull/10, with bug fix applied for Jakarta Servlet API **5.x** - this should be merged to https://github.com/geckoprojects-org/org.gecko.graphql/tree/master branch.

My previous comment (https://github.com/geckoprojects-org/org.gecko.graphql/issues/9#issuecomment-1685324830) mentions same bug fix applied for Jakarta Servlet API **6.x** via latest commit in PR https://github.com/geckoprojects-org/org.gecko.graphql/pull/8 - that PR should be merged to https://github.com/geckoprojects-org/org.gecko.graphql/tree/jakarta-servlet-6 branch.

**Comment by ideas-into-software** [comment]
Closing as both https://github.com/geckoprojects-org/org.gecko.graphql/pull/8 and https://github.com/geckoprojects-org/org.gecko.graphql/pull/10 are merged
